<?php

namespace App\Enum;

enum PayPalEventEnum: string
{
    case ORDER_APPROVED = 'CHECKOUT.ORDER.APPROVED';
    case CAPTURE_COMPLETED = 'PAYMENT.CAPTURE.COMPLETED';
    case CAPTURE_PENDING = 'PAYMENT.CAPTURE.PENDING';
    case CAPTURE_DECLINED = 'PAYMENT.CAPTURE.DECLINED';
    case CAPTURE_DENIED = 'PAYMENT.CAPTURE.DENIED';
    case CAPTURE_REFUNDED = 'PAYMENT.CAPTURE.REFUNDED';
    case CAPTURE_REVERSED = 'PAYMENT.CAPTURE.REVERSED';
}
